export interface Product {
  id: string;
  name: string;
  price: number;
  category: "thé" | "matcha" | "accessoires" | "biscuits";
  description: string;
  image: string;
  taste?: string;
  origin?: string;
  grade?: "basic" | "middle" | "premium";
  inStock: boolean;
}

export const products: Product[] = [
  // Thés (20 produits)
  {
    id: "1",
    name: "Thé Vert Sencha Premium",
    price: 24.99,
    category: "thé",
    description: "Thé vert japonais aux notes fraîches et herbacées",
    image: "/images/sencha.jpg",
    taste: "herbacé",
    origin: "Japon",
    inStock: true,
  },
  {
    id: "2",
    name: "Thé Vert Gyokuro",
    price: 49.99,
    category: "thé",
    description: "Thé d'ombre de haute qualité, saveur umami intense",
    image: "/images/gyokuro.jpg",
    taste: "umami",
    origin: "Japon",
    inStock: true,
  },
  {
    id: "3",
    name: "Thé Vert Hojicha",
    price: 18.99,
    category: "thé",
    description: "Thé grillé aux arômes de noisette",
    image: "/images/hojicha.jpg",
    taste: "grillé",
    origin: "Japon",
    inStock: true,
  },
  {
    id: "4",
    name: "Thé Blanc Pai Mu Tan",
    price: 32.99,
    category: "thé",
    description: "Thé blanc délicat aux notes florales",
    image: "/images/paimutan.jpg",
    taste: "floral",
    origin: "Chine",
    inStock: true,
  },
  {
    id: "5",
    name: "Thé Oolong Tie Guan Yin",
    price: 28.99,
    category: "thé",
    description: "Thé semi-fermenté aux arômes complexes",
    image: "/images/tieguanyin.jpg",
    taste: "fruité",
    origin: "Chine",
    inStock: true,
  },
  {
    id: "6",
    name: "Thé Vert Dragon Well",
    price: 26.99,
    category: "thé",
    description: "Thé vert chinois classique, saveur douce",
    image: "/images/dragonwell.jpg",
    taste: "doux",
    origin: "Chine",
    inStock: true,
  },
  {
    id: "7",
    name: "Thé Vert Genmaicha",
    price: 22.99,
    category: "thé",
    description: "Mélange de thé vert et riz grillé",
    image: "/images/genmaicha.jpg",
    taste: "grillé",
    origin: "Japon",
    inStock: true,
  },
  {
    id: "8",
    name: "Thé Blanc Silver Needle",
    price: 45.99,
    category: "thé",
    description: "Thé blanc premium aux bourgeons argentés",
    image: "/images/silverneedle.jpg",
    taste: "délicat",
    origin: "Chine",
    inStock: true,
  },
  {
    id: "9",
    name: "Thé Vert Kabusecha",
    price: 34.99,
    category: "thé",
    description: "Thé d'ombre léger, entre sencha et gyokuro",
    image: "/images/kabusecha.jpg",
    taste: "umami",
    origin: "Japon",
    inStock: true,
  },
  {
    id: "10",
    name: "Thé Oolong Da Hong Pao",
    price: 52.99,
    category: "thé",
    description: "Thé oolong de roche aux arômes minéraux",
    image: "/images/dahongpao.jpg",
    taste: "minéral",
    origin: "Chine",
    inStock: true,
  },
  {
    id: "11",
    name: "Thé Vert Shincha",
    price: 38.99,
    category: "thé",
    description: "Première récolte de l'année, fraîcheur exceptionnelle",
    image: "/images/shincha.jpg",
    taste: "frais",
    origin: "Japon",
    inStock: true,
  },
  {
    id: "12",
    name: "Thé Blanc Moonlight White",
    price: 29.99,
    category: "thé",
    description: "Thé blanc du Yunnan aux notes sucrées",
    image: "/images/moonlight.jpg",
    taste: "sucré",
    origin: "Chine",
    inStock: true,
  },
  {
    id: "13",
    name: "Thé Vert Kukicha",
    price: 19.99,
    category: "thé",
    description: "Thé de tiges, faible en caféine",
    image: "/images/kukicha.jpg",
    taste: "doux",
    origin: "Japon",
    inStock: true,
  },
  {
    id: "14",
    name: "Thé Oolong Iron Buddha",
    price: 31.99,
    category: "thé",
    description: "Oolong traditionnel aux notes florales",
    image: "/images/ironbuddha.jpg",
    taste: "floral",
    origin: "Chine",
    inStock: true,
  },
  {
    id: "15",
    name: "Thé Vert Tamaryokucha",
    price: 25.99,
    category: "thé",
    description: "Thé vert aux feuilles bouclées",
    image: "/images/tamaryokucha.jpg",
    taste: "herbacé",
    origin: "Japon",
    inStock: true,
  },
  {
    id: "16",
    name: "Thé Blanc Shou Mei",
    price: 23.99,
    category: "thé",
    description: "Thé blanc vieilli aux arômes complexes",
    image: "/images/shoumei.jpg",
    taste: "complexe",
    origin: "Chine",
    inStock: true,
  },
  {
    id: "17",
    name: "Thé Vert Fukamushi",
    price: 27.99,
    category: "thé",
    description: "Sencha à vapeur prolongée, couleur intense",
    image: "/images/fukamushi.jpg",
    taste: "intense",
    origin: "Japon",
    inStock: true,
  },
  {
    id: "18",
    name: "Thé Oolong Oriental Beauty",
    price: 42.99,
    category: "thé",
    description: "Oolong unique aux notes de miel",
    image: "/images/orientalbeauty.jpg",
    taste: "miel",
    origin: "Taïwan",
    inStock: true,
  },
  {
    id: "19",
    name: "Thé Vert Bancha",
    price: 16.99,
    category: "thé",
    description: "Thé de tous les jours, saveur équilibrée",
    image: "/images/bancha.jpg",
    taste: "équilibré",
    origin: "Japon",
    inStock: true,
  },
  {
    id: "20",
    name: "Thé Blanc Gong Mei",
    price: 21.99,
    category: "thé",
    description: "Thé blanc traditionnel du Fujian",
    image: "/images/gongmei.jpg",
    taste: "traditionnel",
    origin: "Chine",
    inStock: true,
  },

  // Matchas (3 produits)
  {
    id: "21",
    name: "Matcha Basic",
    price: 19.99,
    category: "matcha",
    description: "Matcha d'entrée de gamme, parfait pour débuter",
    image: "/images/matcha-basic.jpg",
    grade: "basic",
    origin: "Japon",
    inStock: true,
  },
  {
    id: "22",
    name: "Matcha Premium",
    price: 29.99,
    category: "matcha",
    description: "Matcha de qualité supérieure pour les connaisseurs",
    image: "/images/matcha-premium.jpg",
    grade: "middle",
    origin: "Japon",
    inStock: true,
  },
  {
    id: "23",
    name: "Matcha Ceremony Grade",
    price: 49.99,
    category: "matcha",
    description: "Matcha de cérémonie, la plus haute qualité",
    image: "/images/matcha-ceremony.jpg",
    grade: "premium",
    origin: "Japon",
    inStock: true,
  },

  // Accessoires (5 produits)
  {
    id: "24",
    name: "Bol à Matcha (Chawan)",
    price: 24.99,
    category: "accessoires",
    description: "Bol traditionnel en céramique pour la préparation du matcha",
    image: "/images/chawan.jpg",
    inStock: true,
  },
  {
    id: "25",
    name: "Fouet en Bambou (Chasen)",
    price: 19.99,
    category: "accessoires",
    description: "Fouet traditionnel en bambou pour battre le matcha",
    image: "/images/chasen.jpg",
    inStock: true,
  },
  {
    id: "26",
    name: "Cuillère à Matcha (Chashaku)",
    price: 12.99,
    category: "accessoires",
    description: "Cuillère en bambou pour doser le matcha",
    image: "/images/chashaku.jpg",
    inStock: true,
  },
  {
    id: "27",
    name: "Set Matcha Complet",
    price: 54.99,
    category: "accessoires",
    description: "Kit complet avec bol, fouet et cuillère",
    image: "/images/set-matcha.jpg",
    inStock: true,
  },
  {
    id: "28",
    name: "Théière en Fonte",
    price: 89.99,
    category: "accessoires",
    description: "Théière traditionnelle en fonte pour infuser le thé",
    image: "/images/theiere-fonte.jpg",
    inStock: true,
  },

  // Biscuits (5 produits)
  {
    id: "29",
    name: "Mochi au Matcha",
    price: 8.99,
    category: "biscuits",
    description: "Délicieux mochi japonais parfumé au matcha",
    image: "/images/mochi-matcha.jpg",
    taste: "matcha",
    origin: "Japon",
    inStock: true,
  },
  {
    id: "30",
    name: "Cookies Matcha-Chocolat Blanc",
    price: 12.99,
    category: "biscuits",
    description: "Cookies croustillants au matcha et chocolat blanc",
    image: "/images/cookies-matcha.jpg",
    taste: "sucré",
    origin: "France",
    inStock: true,
  },
  {
    id: "31",
    name: "Dorayaki Traditionnel",
    price: 15.99,
    category: "biscuits",
    description: "Pancakes japonais fourrés à la pâte de haricot rouge",
    image: "/images/dorayaki.jpg",
    taste: "traditionnel",
    origin: "Japon",
    inStock: true,
  },
  {
    id: "32",
    name: "Sablés au Thé Vert",
    price: 9.99,
    category: "biscuits",
    description: "Sablés français délicatement parfumés au thé vert",
    image: "/images/sables-the.jpg",
    taste: "délicat",
    origin: "France",
    inStock: true,
  },
  {
    id: "33",
    name: "Wagashi Assortis",
    price: 18.99,
    category: "biscuits",
    description: "Assortiment de confiseries japonaises traditionnelles",
    image: "/images/wagashi.jpg",
    taste: "varié",
    origin: "Japon",
    inStock: true,
  },
];

export const categories = ["thé", "matcha", "accessoires", "biscuits"] as const;
export const tastes = [
  "herbacé",
  "umami",
  "grillé",
  "floral",
  "fruité",
  "doux",
  "délicat",
  "frais",
  "sucré",
  "minéral",
  "complexe",
  "intense",
  "miel",
  "équilibré",
  "traditionnel",
  "matcha",
  "varié",
] as const;
export const origins = ["Japon", "Chine", "Taïwan", "France"] as const;
export const priceRanges = [
  { label: "Moins de 20€", min: 0, max: 20 },
  { label: "20€ - 30€", min: 20, max: 30 },
  { label: "30€ - 50€", min: 30, max: 50 },
  { label: "Plus de 50€", min: 50, max: Infinity },
] as const;
